# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."cryptdev".device = "/dev/disk/by-uuid/4d257de1-5a22-4854-a248-1acbea7133de";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f5803a88-0484-4b71-9a6d-a87723d721b4";
      fsType = "btrfs";
      options = [ "subvol=nixos_root" "compress=zstd" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f5803a88-0484-4b71-9a6d-a87723d721b4";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "ssd" "space_cache=v2" "noatime" ];
    };

  fileSystems."/btr_pool" =
    { device = "/dev/disk/by-uuid/f5803a88-0484-4b71-9a6d-a87723d721b4";
      fsType = "btrfs";
      options = [ "subvolid=5" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CE12-EEE6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
