# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7555cb72-3b26-4fb8-bf5a-36932d17c38c";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/626c7b8d-04c7-40bf-92a5-1447cdc3c53f";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/626c7b8d-04c7-40bf-92a5-1447cdc3c53f";
    fsType = "btrfs";
    options = [
      "subvol=@docker"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/media/nas_localdrive" = {
    device = "/dev/disk/by-uuid/626c7b8d-04c7-40bf-92a5-1447cdc3c53f";
    fsType = "btrfs";
    options = [
      "subvol=@nas"
      "compress=zstd"
      "noatime"
    ];
  };

  fileSystems."/btr_pool0" = {
    device = "/dev/disk/by-uuid/626c7b8d-04c7-40bf-92a5-1447cdc3c53f";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3743-AE4D";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/btr_pool1" = {
    device = "/dev/disk/by-uuid/604e2efa-2433-44df-b614-6c2e70bb9f04";
    fsType = "btrfs";
    options = [
      "nofail"
    ];
  };

  fileSystems."/media/nas_ext1" = {
    device = "/dev/disk/by-uuid/604e2efa-2433-44df-b614-6c2e70bb9f04";
    fsType = "btrfs";
    options = [
      "subvol=@nas"
      "compress=zstd"
      "noatime"
      "nofail"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/bb9a64bb-72cb-4f0d-a666-ee6a3959d941"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
